export const SIZE_DESC: readonly string[] = [
  'Asteroid · 800 km · negligible g',
  'Tiny · 1,600 km · 0.05 g',
  'Small moon · 3,200 km · 0.15 g',
  'Mercury-like · 4,800 km · 0.25 g',
  'Mars-like · 6,400 km · 0.35 g',
  '8,000 km · 0.45 g',
  '9,600 km · 0.7 g',
  '11,200 km · 0.9 g',
  'Earth-like · 12,800 km · 1.0 g',
  'Super-Earth · 14,400 km · 1.25 g',
  'Large · 16,000 km · 1.4 g',
]

export const ATM_DESC: readonly string[] = [
  'None — vacuum',
  'Trace',
  'Very thin, tainted',
  'Very thin',
  'Thin, tainted',
  'Thin',
  'Standard (Earth-like)',
  'Standard, tainted',
  'Dense',
  'Dense, tainted',
  'Exotic',
  'Corrosive',
  'Insidious',
  'Dense high (highland habitable)',
  'Thin low (lowland habitable)',
  'Unusual / gas giant',
]

export const HYDRO_DESC: readonly string[] = [
  'Desert · 0–5%',
  'Dry · 6–15%',
  'Few small seas · 16–25%',
  'Small oceans · 26–35%',
  'Wet · 36–45%',
  'Large oceans · 46–55%',
  '56–65%',
  '66–75%',
  'Water world · 76–85%',
  'Islands / archipelagos · 86–95%',
  'Almost entirely water · 96–100%',
]

export const POP_DESC: readonly string[] = [
  'Uninhabited',
  'Tens (10s)',
  'Hundreds (100s)',
  'Thousands',
  'Ten thousands',
  'Hundred thousands',
  'Millions',
  'Tens of millions',
  'Hundreds of millions',
  'Billions',
  'Tens of billions',
  'Hundreds of billions',
  'Trillions',
]

export const GOV_DESC: readonly string[] = [
  'None',
  'Company / corporation',
  'Participating democracy',
  'Self-perpetuating oligarchy',
  'Representative democracy',
  'Feudal technocracy',
  'Captive government',
  'Balkanization',
  'Civil service bureaucracy',
  'Impersonal bureaucracy',
  'Charismatic dictator',
  'Non-charismatic leader',
  'Charismatic oligarchy',
  'Religious dictatorship',
  'Religious autocracy',
  'Totalitarian oligarchy',
]

export const LAW_DESC: readonly string[] = [
  'No law',
  'Low law',
  'Most weapons restricted',
  'Heavy weapons restricted',
  'Light assault weapons restricted',
  'Personal concealable weapons restricted',
  'All firearms restricted',
  'Shock weapons restricted',
  'Blade weapons restricted',
  'Sport weapons restricted',
  'Most sport weapons restricted',
  'High law',
  'Very high law',
  'Extreme law',
  'Police state',
  'Total prohibition',
]

export const TECH_DESC: readonly string[] = [
  'TL 0 · stone age',
  'TL 1 · bronze, iron',
  'TL 2 · pre-industrial',
  'TL 3 · industrial age',
  'TL 4 · mechanised',
  'TL 5 · atomic age',
  'TL 6 · early computers',
  'TL 7 · space probes',
  'TL 8 · lunar landing',
  'TL 9 · early interplanetary',
  'TL A · interstellar',
  'TL B · average imperial',
  'TL C · high imperial',
  'TL D · common interstellar',
  'TL E · anti-grav',
  'TL F · ultra-tech',
]
